MarkDownTranslator "PageNotFound.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_CheckerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_Job.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_JobConnector.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_JobList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_JobPackage.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_LoggerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_LogicalNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_LogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_NodeCheckerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_NodeConnector.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_NodeList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_NodeParent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_NodeShellBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_SingleNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_Snapshot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_TreeEventTrigger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_TriggerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_UndefinedJob.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_UndefinedJobListClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_UndefinedLogicalNodeClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_ValueModifier_1.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_Workers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_LogicalTaskTree_WorkerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_Abortable.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_InfoArgs.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_Logger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_LoggerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_Statistics.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationControl_TaskWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_AppEnvReader.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_BasicAppSettings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_ClickOnceInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_CommandLineAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_EnvAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_PropertyAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_RegAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ApplicationEnvironment_SettingsAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_CustomControls_CustomProgressBar.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_CustomControls_SplashScreenMessage.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_CustomControls_SplashWindow.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_CustomControls_ZoomBox.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_ArithmeticParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_BooleanParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_ExpressionParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_LogicalParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_SyntaxTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_ExpressionParser_TresholdParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_FileTools_IniAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_FileTools_XmlAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_FileTools_Zip_ZippedFileInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_Globals_GenericTree_1.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_Globals_IGetStringValue.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_MultiScreen_ScreenInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_NetEti_MVVMini_PropertiesChangedEventArgs.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_AppSettings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_IExpandableNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_INodeChecker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_INodeTrigger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_IVishnuNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_IVishnuViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_Result.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_TreeEvent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_TreeParameters.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_TriggerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_TriggerInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_UndefinedTreeEventClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_Interchange_WindowAspects.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_ConstantNodeUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_JobConnectorUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_JobListUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_NodeListUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_SingleNodeUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_UserControls_SnapshotUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_DummyLogicalTaskTreeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_DynamicUserControlBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_JobConnectorViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_JobGroupViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_JobListViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_LogicalNodeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_LogicalTaskTreeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_MainWindowViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_NodeErrorViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_NodeListViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_OrientedTreeViewModelBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_SingleNodeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_SnapshotViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_ViewModel_VishnuViewModelBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_WPF_UI_DependencyProperties_BinaryModificationSwitch.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_WPF_UI_LogicalTaskJobGroupsControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_WPF_UI_MainWindow.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "Properties_T_Vishnu_WPF_UI_NodeErrorControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_SingleInstance.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_StatisticsFile.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_StatisticsFileRegexFilter.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_TempDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_UserDomainName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_UserName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_UserSettingsAccessor.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_WorkingDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_BasicAppSettings_WorkingDirectoryCreated.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_ActivationData.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_ActivationUri.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_ApplicationName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_BaseDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_CurrentVersion.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_DataDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_IsNetworkDeployed.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_TargetFrameworkName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_TimeOfLastUpdateCheck.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_UpdatedApplicationFullName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_UpdatedVersion.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceInfo_UpdateLocation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo_CurrentVersion.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo_IsMandatoryUpdate.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo_IsUpdateAvailable.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo_LatestVersion.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo_MinimumVersion.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_CommandLineAccess_CommandLine.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_CommandLineAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_EnvAccess_ActivationData.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_EnvAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_PropertyAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_RegAccess_CurrentRegistryRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_RegAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_RegAccess_RegistryBasePath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_SettingsAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ApplicationEnvironment_SettingsAccess_Settings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_CustomProgressBar_IsGlowing.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_CustomProgressBar_IsIndeterminate.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_CustomProgressBar_Text.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_CustomProgressBar_Value.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_SplashScreenMessage_Message.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_SplashWindow_Version.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_HorizontalScroll.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_HorizontalScrollBarVisibility.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_IsHorizontalScrollbarVisible.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_IsVerticalScrollbarVisible.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_MinimalScaleFactor.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_VerticalScroll.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_CustomControls_ZoomBox_VerticalScrollBarVisibility.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_ExpressionParser_ExpressionString.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_ExpressionParser_MetaRules.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_ExpressionParser_OperatorPriority.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_ExpressionParser_Operators.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_ExpressionParser_Token.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_SyntaxTree_NodeName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_ExpressionParser_SyntaxTree_NodeType.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_IniAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_XmlAccess_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_XmlAccess_Settings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_Zip_ZippedFileInfo_FilePath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_Zip_ZippedFileInfo_IsDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_Zip_ZippedFileInfo_LastWriteTime.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_FileTools_Zip_ZippedFileInfo_Size.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_Globals_GenericTree_1_Children.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_Globals_IGetStringValue_Description.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_MultiScreen_ScreenInfo_Bounds.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_MultiScreen_ScreenInfo_IsPrimary.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_MultiScreen_ScreenInfo_Name.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_MultiScreen_ScreenInfo_WorkingArea.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_NetEti_MVVMini_PropertiesChangedEventArgs_Properties.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_AbortingAllowed.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_ActScreenBounds.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_AssemblyDirectories.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_Autostart.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_ControlledNodeUserRunDialog.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_DemoModus.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_FatalInitializationException.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_FlatNodeListFilter.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_HelpPreference.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_IsInSleepTime.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_LocalConfigurationDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_NoWorkers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_ResolvedSnapshotDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_RootJobXmlName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_SleepTimeFrom.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_SleepTimeTo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_SnapshotDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_SnapshotSustain.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_StartTreeOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_StartTriggeredNodesOnUserRun.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_StartWithJobs.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_UncachedCheckers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_UserAssemblyDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_UserParameterReaderPath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_VishnuProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_VishnuRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_VishnuSourceRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_AppSettings_VishnuWindowAspects.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IExpandableNode_ChildOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IExpandableNode_Id.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IExpandableNode_IsExpanded.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IExpandableNode_Name.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IExpandableNode_Path.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_INodeChecker_ReturnObject.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_INodeTrigger_Info.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuNode_IdInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuNode_LevelInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuNode_NameInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuNode_PathInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuNode_TypeInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuViewModel_ParentView.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuViewModel_Result.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_IVishnuViewModel_UserDataContext.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_Id.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_Logical.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_LogicalState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_ReturnObject.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_State.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_Result_Timestamp.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_Environment.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_Logical.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_Name.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_NodeName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_NodePath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_Results.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_SenderId.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_SourceId.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_State.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_ThreadId.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeEvent_Timestamp.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_BusinessLogicRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_CheckerDllDirectory.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_LastParentViewAbsoluteScreenPosition.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_Name.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_ParentView.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TreeParameters_ViewModelRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TriggerBase_Info.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TriggerBase_TriggerName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TriggerInfo_NextRun.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_TriggerInfo_NextRunInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_ActScreenIndex.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_ActTabControlTab.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_IsScrollbarVisible.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowCenterX.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowCenterY.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowHeight.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowScrollLeft.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowScrollTop.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowWidth.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_Interchange_WindowAspects_WindowZoom.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_DynamicUserControlBase_AttachedName.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_DynamicUserControlBase_UserResultViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobConnectorViewModel_ReferencedNodePath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_DebugMode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_DebugNodeInfos.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_FlatNodeViewModelList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_GridColumnCount.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_GridRowCount.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_GroupJobList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_IsTreePaused.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobGroupViewModel_LastExceptions.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_BreakLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_ButtonBreakText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_ButtonRunBreakText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_ButtonRunText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_IsActive.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_RunLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_JobListViewModel_RunOrBreakLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_ChildOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Children.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_CollapsedEventCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_DebugMode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_DebugNodeInfos.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_ExpandedEventCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_FreeComment.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_HasParent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_HookedTo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Id.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_IsExpanded.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_IsInSleepTime.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_IsSelected.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_IsSnapshotDummy.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_IsTreePaused.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_LastExceptions.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_LastExecutingTreeEvent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_LastNotNullLogical.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_LastRun.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_LastRunInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Logical.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Name.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_NextRun.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_NextRunInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_NextRunInfoAndResult.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_NodeEnvironment.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_OriginalNodeId.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Parent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Path.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Progress.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_ProgressText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Result.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Results.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_RootJobListViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_ShortResult.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_SingleNodes.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_SingleNodesFinished.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_SizeChangedEventCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_SleepTimeTo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_StartTreeOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_TreeParams.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_UIDispatcher.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_UIMain.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_UserControlPath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_Visibility.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_VisualState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalNodeViewModel_WorkersState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalTaskTreeViewModel_BreakLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalTaskTreeViewModel_InfoSource.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalTaskTreeViewModel_IsInSleepTime.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalTaskTreeViewModel_RunLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_LogicalTaskTreeViewModel_SleepTimeTo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_BreakJobGroups.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_InitSizeCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_JobGroupsVM.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_RunJobGroups.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_ShowVishnuHelpCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_SwitchTaskTreeViewRoutedCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_TreeParams.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_TreeVM.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_MainWindowViewModel_WindowTitle.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_NodeErrorViewModel_DllPath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_OrientedTreeViewModelBase_MainLogicalNodeView.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_OrientedTreeViewModelBase_TreeOrientationState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_OrientedTreeViewModelBase_TreeParams.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_OrientedTreeViewModelBase_TreeVM.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_BreakLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_ButtonBreakText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_ButtonRunBreakText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_ButtonRunText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_RunLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SingleNodeViewModel_RunOrBreakLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SnapshotViewModel_IsDefaultSnapshot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SnapshotViewModel_IsInSnapshot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SnapshotViewModel_RefreshSnapshot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SnapshotViewModel_SnapshotPath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_SnapshotViewModel_SnapshotTime.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ClearInfos.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_CopyToolTipInfoToClipboard.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_GridColumn.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_GridRow.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_IsRendered.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_JobInProgress.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_LogLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ParentView.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_PauseResumeLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ReloadLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_Result.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_RootLogicalTaskTreeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ShowInfos.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ShowLogLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ShowSettingsLogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ShowVishnuHelp.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_SwitchTaskTreeView.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_ToolTipInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_UserDataContext.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_ViewModel_VishnuViewModelBase_VisualTreeCacheBreaker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_Behaviours_CenterOnSizeChangeBehaviour_CenterOnSizeChange.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_Behaviours_ExpanderBehaviour_CollapsedCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_Behaviours_ExpanderBehaviour_ExpandedCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_Behaviours_ExpanderBehaviour_SizeChangedCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_AttachedPropertiesContainer_HasParent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_AttachedPropertiesContainer_LastNotNullLogical.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_AttachedPropertiesContainer_ParentChildOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_BinaryModificationSwitch_OrientationModification.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_GridHelpers_ColumnCount.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_GridHelpers_ColumnsProperties.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_GridHelpers_RowCount.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_DependencyProperties_GridHelpers_RowsProperties.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_MainWindow_FirstSelectedIndex.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_MainWindow_MainWindowAspects.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_MainWindow_MinLeft.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_MainWindow_MinTop.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_MainWindow_SizeOnVirtualScreen.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_NodeErrorControl_DllPath.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "P_Vishnu_WPF_UI_NodeErrorControl_NodeErrorUserResultViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "R_Project_Vishnu_doc_de.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_AllStatesChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_CheckerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_ConfigurationManager.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_ExceptionRaisedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_IJobProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_Job.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_JobConnector.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_JobList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_JobPackage.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_JobProviderBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_JobProviderBase_UndefinedJobProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LastNotNullLogicalChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LoggerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LogicalChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LogicalNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LogicalStateChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_LogicalTaskTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeCheckerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeConnector.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeList.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeParent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeResultComparer.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_NodeShellBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_Provider_EmptyJobProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_Provider_ProductionJobProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_ResultChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_SingleNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_Snapshot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_SnapshotRefreshedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_StateChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_ThreadLocker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_TreeEventTrigger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_TriggerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_UndefinedJob.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_UndefinedJobListClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_UndefinedLogicalNodeClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_ValueModifier_1.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_Workers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_LogicalTaskTree_WorkerShell.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_Abortable.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IFlushable.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IInfoController.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IInfoPublisher.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IInfoSource.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IInfoViewer.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_InfoArgs.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_InfoController.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_InfoType.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_InfoTypes.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_IShowable.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_Logger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_LoggerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_Messaging.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_ProcessWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_Statistics.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_TaskWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_TaskWorkerStatus.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationControl_ViewerAsWrapper.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_AppEnvReader.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_AppSettingsRegistry.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_BasicAppSettings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_ClickOnceDeploymentException.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_ClickOnceInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_ClickOnceUpdateInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_CommandLineAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_EnvAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_PropertyAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_RegAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_RegistryRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ApplicationEnvironment_SettingsAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_CustomControls_CustomProgressBar.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_CustomControls_SplashScreenMessage.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_CustomControls_SplashWindow.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_CustomControls_VishnuHelpBrowser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_CustomControls_ZoomBox.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_ArithmeticParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_BooleanParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_ExpressionParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_LogicalParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_SyntaxElement.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_SyntaxTree.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ExpressionParser_TresholdParser.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_EditorCaller.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_IniAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_XmlAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_ICSharpWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_MSCompressionWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_SevenZipWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_StaticZipHelpers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_ZipAccess.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_FileTools_Zip_ZippedFileInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_AssemblyLoader.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_DictionaryThreadSafeCopy_2.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_EnumerableThreadSafeCopy_1.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_GenericNonSingletonProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_GenericSingletonProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_GenericTree_1.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_Global.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_IGetStringValue.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_IGetValue.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_IUndefinedElement.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_ThreadInfos.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_Globals_ThreadLocker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MultiScreen_ScreenInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_INotifyPropertiesChanged.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_IRelayCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_ObservableObject.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_PropertiesChangedEventArgs.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_PropertiesChangedEventHandler.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_PropertySupport.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_MVVMini_RelayCommand.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ObjectSerializer_AnonymousDataMemberAttribute.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_NetEti_ObjectSerializer_SerializationUtility.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_AppSettings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_DialogSettings.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_GenericPropertyGetter.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IBusinessLogicRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_ICanRun.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IExpandableNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_INodeChecker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_INodeLogger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_INodeTrigger.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_INodeWorker.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IParameterReader.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IValueModifier.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IViewModelRoot.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IVishnuJobProvider.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IVishnuNode.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_IVishnuViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_NodeLogicalState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_NodeState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_NodeTypes.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_NodeWorkerState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_OrientationSwitch.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_Result.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_ResultDictionary.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TreeEvent.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TreeOrientation.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TreeParameters.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TriggerBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TriggeredNodeStartConstraint.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_TriggerInfo.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_UndefinedTreeEventClass.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_VishnuAssemblyLoader.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_Interchange_WindowAspects.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_ConstantNodeUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_JobConnectorUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_JobListUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_NodeListUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_SingleNodeUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_UserControls_SnapshotUserControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_DummyLogicalTaskTreeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_DynamicUserControlBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_DynamicUserControlViewModelBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_IVishnuRenderWatcher.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_JobConnectorViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_JobGroupViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_JobListViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_LogicalNodeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_LogicalTaskTreeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_MainWindowViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_NodeErrorViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_NodeListViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_OrientedTreeViewModelBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_SingleNodeViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_SnapshotViewModel.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_UIHelper.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_VishnuViewModelBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_VisualNodeState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_ViewModel_VisualNodeWorkerState.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_Behaviours_CenterOnSizeChangeBehaviour.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_Behaviours_ExpanderBehaviour.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_DependencyProperties_AttachedPropertiesContainer.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_DependencyProperties_BinaryModificationSwitch.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_DependencyProperties_GridHelpers.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_DependencyProperties_OrientationSwitchTypeConverter.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_LogicalTaskJobGroupsControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_LogicalTaskTreeControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_MainWindow.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_NodeErrorControl.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_ChildOrientationToExpandDirection.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_EqualityConverter.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_NotEmptyToTrue.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_NullableBoolToBrush.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_OrientationModifier.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_Path2UserControlBase.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_VisualNodeStateToBitmapImage.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
MarkDownTranslator "T_Vishnu_WPF_UI_ValueConverter_VisualNodeWorkerStateToText.htm" -SourceLanguageCode=de -TargetLanguageCode=en-GB 
